-- Recurring rent payments are auto-generated by the Intouch callback (next
-- month) and by /api/payments/advance, both using a check-then-insert
-- pattern with no DB-level guard. Two concurrent callbacks (or a retried
-- webhook) can both pass the "no existing payment" check and insert two
-- rows for the same lease + due date.
--
-- Deposit/advance/agency-fee payments (CAUTION-/AVANCE-/AGENCE- references)
-- legitimately share the same due_date as each other for a given lease, so
-- the constraint is scoped to the regular recurring rent rows, which never
-- carry a reference at creation time (it's only set once Intouch confirms
-- payment).
create unique index if not exists idx_payments_lease_due_date_unassigned
  on payments (lease_id, due_date)
  where reference is null;
