// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const env = import.meta.env;
const SUPABASE_URL = env.VITE_SUPABASE_URL || env.VITE_PUBLIC_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = env.VITE_SUPABASE_ANON_KEY ||
  env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  env.VITE_PUBLIC_SUPABASE_ANON_KEY ||
  env.VITE_PUBLIC_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    "Supabase configuration is missing. Please set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY.",
  );
}

// Aggressive token cleanup - remove all Supabase auth data
const aggressiveTokenCleanup = () => {
  try {
    // Remove all possible Supabase auth keys
    const keysToRemove = [];
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      if (key && (key.includes("supabase") || key.includes("auth"))) {
        keysToRemove.push(key);
      }
    }
    keysToRemove.forEach((key) => {
      try {
        localStorage.removeItem(key);
      } catch (e) {
        // Ignore individual removal errors
      }
    });
    console.log(
      "Cleaned up",
      keysToRemove.length,
      "Supabase/auth items from localStorage",
    );
  } catch (error) {
    console.warn("Could not perform aggressive token cleanup:", error);
  }
};

// Export the Supabase URL for use in other configurations
export const SUPABASE_API_URL = SUPABASE_URL;

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
    global: {
      headers: {
        "x-connect-timeout": "30s",
        "x-read-timeout": "60s",
      },
      // Custom fetch to handle timeout headers for Edge Functions
      fetch: (url, options = {}) => {
        const newOptions = { ...options };
        const headers = new Headers(newOptions.headers as HeadersInit);
        const urlString = typeof url === "string"
          ? url
          : url instanceof URL
          ? url.toString()
          : url.url;
        const isFunctionCall = urlString.includes("/functions/v1/");

        if (isFunctionCall) {
          headers.delete("x-connect-timeout");
          headers.delete("x-read-timeout");
        }

        newOptions.headers = headers;
        return fetch(url, newOptions);
      },
    },
    db: {
      schema: "public",
    },
    realtime: {
      params: {
        eventsPerSecond: 10,
      },
    },
  },
);

// Handle auth errors more gracefully
supabase.auth.onAuthStateChange((event, session) => {
  // Only perform cleanup on actual sign out, not on token refresh
  if (event === "SIGNED_OUT" && !session) {
    console.log("User signed out, performing token cleanup");
    aggressiveTokenCleanup();
  }
});
