// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const env = import.meta.env;
const SUPABASE_URL = env.VITE_SUPABASE_URL || env.SUPABASE_URL || env.VITE_PUBLIC_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  env.VITE_SUPABASE_ANON_KEY ||
  env.SUPABASE_ANON_KEY ||
  env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  env.VITE_PUBLIC_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Supabase configuration is missing. Please set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY.'
  );
}

// Export the Supabase URL for use in other configurations
export const SUPABASE_API_URL = SUPABASE_URL;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  global: {
    headers: {
      'x-connect-timeout': '30s',
      'x-read-timeout': '60s',
    },
    // Custom fetch to handle timeout headers for Edge Functions
    fetch: (url, options = {}) => {
      const newOptions = { ...options };
      const headers = new Headers(newOptions.headers as HeadersInit);
      const urlString =
        typeof url === 'string' ? url : url instanceof URL ? url.toString() : url.url;
      const isFunctionCall = urlString.includes('/functions/v1/');

      if (isFunctionCall) {
        headers.delete('x-connect-timeout');
        headers.delete('x-read-timeout');
      }

      newOptions.headers = headers;
      return fetch(url, newOptions);
    },
  },
  db: {
    schema: 'public',
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
});
